{% set version = "1.11.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ks
  version: {{ version|replace("-", "_") }}

source:
  fn: ks_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ks_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ks/ks_{{ version }}.tar.gz
  sha256: 0d69e85fb4dc97045fdc273b36cf44b185ab60a6d7b17e1eb0c6dddf074be47c

build:
  merge_build_host: True  # [win]
  number: 1
  # r-rgl is not available on win and osx
  skip: true  # [win or osx]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-fnn >=1.1
    - r-kernsmooth >=2.22
    - r-misc3d >=0.4_0
    - r-multicool
    - r-mvtnorm >=1.0_0
    - r-rgl >=0.66
    - r-kernlab
    - r-mclust

  run:
    - r-base
    - r-fnn >=1.1
    - r-kernsmooth >=2.22
    - r-misc3d >=0.4_0
    - r-multicool
    - r-mvtnorm >=1.0_0
    - r-rgl >=0.66
    - r-kernlab
    - r-mclust

test:
  commands:
    - $R -e "library('ks')"  # [not win]
    - "\"%R%\" -e \"library('ks')\""  # [win]

about:
  home: http://www.mvstat.net/tduong
  license: GPL-2 | GPL-3
  summary: 'Kernel smoothers for univariate and multivariate data, including density functions,
    density derivatives, cumulative distributions, modal clustering, discriminant analysis,
    significant modal regions and two-sample hypothesis testing.   '

  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
