travis:
  secure:
    BINSTAR_TOKEN: c4VVCBT6xu9Zve1YqWS6Bx0pRIcrdaI2D40B+mlPWXNgpEej+m1uwFzbdcAEs5UYxdB/XovIOPFKFn6sGW1iempF3Nh++e2OL1GsnTF281ii32EfHjIxsclWFlCKbwYVfsEHY6Ua7ZXwssqZf2LDdrBEf8F+7ptOsgWMAuHkyrjb3V69LpyXi1NooEQkzHIVoNaG0pGZrq4PxuxeVtWQ3JyD2d5bkUNiv02b/zMRfhmVG9uLw0Avtnyy5nuziBWtAPyytk55gq4U7zWL57X5m6rlWWLaLFrhgsprTBOdr+PbqDwVEW+b7J3LbVKC7HRUK6qN43aTteRMV379woFFGaQNbqHwQ7b1/L3ATYLcSMbGNcBdFN9X38Ijepnd/morHmgqn6I9HE9TGGToUjQTyXG3zVJdblslVjMo3AnzYUiwprzTMBB3KcxRW1f0F++myF+sTb3QhCLvyahLbvBBtfNQMHE1jdnS99Keu5abbnTq1bAIDH0xiffVsmYjMubOy4d3erd/bNtAlaZd/HZSfoElU9v/suKui2MnBqacEWYV7hLQ07cmYKCI9c0z9Qg755N+0k83xT05nQzTSNvf884ViSWb4vWqClkzkVEqoU4/hL5aEbp7iB2js1W0CWZpeAC4wNM231JIPCQm0kPqWgpKC5HGh7cA2Bu02MaLrPU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
